import { buildRegistrationFormPdf } from "../src/lib/registration-form-pdf";

const mockApplication = {
  id: "test",
  applicationCode: "VK2026-TEST",
  status: "CHO_KIEM_TRA",
  fullName: "NGUYỄN VĂN A",
  dateOfBirth: new Date("2011-01-01"),
  gender: "NAM",
  ethnicity: "Kinh",
  birthPlace: "Cà Mau",
  citizenId: "012345678901",
  issueDate: new Date("2025-01-01"),
  issuePlace: "Bộ Công an",
  secondarySchool: "THCS Phan Bội Châu",
  secondarySchoolOldAddress: "Phường 1/2, TP Cà Mau, Cà Mau cũ",
  secondarySchoolAddress: "Phường An Xuyên, tỉnh Cà Mau",
  schoolYear: "2025 - 2026",
  permanentAddress: "Số 1, Ấp Long Hòa, Xã Phước Long, Cà Mau",
  houseNumber: "Số 1",
  hamlet: "Ấp Long Hòa",
  ward: "Xã Phước Long",
  province: "Cà Mau",
  studentPhone: "0912345678",
  email: "hocsinh@example.com",
  guardianName: "Nguyễn Văn B",
  guardianPhone: "0987654321",
  selectedOptionNumber: 1,
  selectedSubjects: "Vật lí; Hoá học; Tin học; Công nghệ Công nghiệp",
  bonusScore: 1.5,
  additionalAwardsNote: "",
  commitmentAccepted: true,
  publicNote: null,
  internalNote: null,
  deletedAt: null,
  deletedById: null,
  deleteReason: null,
  submittedAt: new Date(),
  createdAt: new Date(),
  updatedAt: new Date(),
  admissionResult: "CHUA_XET",
  admissionPublished: false,
  admissionPublishedAt: null,
  admissionPublishedById: null,
  admissionDecisionAt: null,
  admissionDecisionById: null,
  admissionNote: null,
  admissionPublicNote: null,
  admissionRank: null,
  admissionBatch: null,
  admissionScoreSnapshot: null,
  physicalDossierStatus: "CHUA_NOP_TRUC_TIEP",
  physicalDossierValidity: "CHUA_KIEM_TRA",
  physicalDossierReceivedAt: null,
  physicalDossierReceivedById: null,
  physicalDossierCheckedAt: null,
  physicalDossierCheckedById: null,
  physicalDossierPublicNote: null,
  physicalDossierInternalNote: null,
  registrationFormPdfPrintedAt: null,
  academicRecords: [6, 7, 8, 9].map((grade) => ({
    id: `record-${grade}`,
    applicationId: "test",
    grade,
    literature: 8,
    math: 8,
    english: 8,
    naturalScience: 8,
    historyGeography: 8,
    civicEducation: 8,
    technology: 8,
    informatics: 8,
    note: "",
    academicLevel: "TOT",
    conductLevel: "TOT",
  })),
  priorities: [],
  awards: [
    {
      id: "award",
      applicationId: "test",
      competitionName: "Học sinh giỏi cấp tỉnh",
      field: "Tin học",
      level: "Tỉnh",
      year: 2026,
      prize: "GIAI_NHAT",
      bonusScore: 1.5,
    },
  ],
  files: [],
  logs: [],
};

const pdf = await buildRegistrationFormPdf(mockApplication as never);
const header = Buffer.from(pdf.slice(0, 4)).toString("utf8");
if (header !== "%PDF") throw new Error("PDF header không hợp lệ");
if (pdf.length < 5000) throw new Error("PDF quá nhỏ, có thể sinh lỗi");
console.log(`registration-form-pdf OK (${pdf.length} bytes)`);
