-- This migration was generated as a duplicate init after
-- 20260527160000_init and is intentionally kept as a no-op so fresh
-- deployments can run the full migration history without attempting to
-- recreate existing enums/tables.
--
-- If an existing database reports a checksum mismatch for this migration,
-- back up the database first, verify the schema manually, then resolve the
-- migration according to docs/database-troubleshooting.md.
